### ISSUE TITLE
Set up server for devhub backend + couchbase

### ISSUE THREAD

**Issue by nsjames** [eosnetworkfoundation/devrel#81] opened 2022-10-20 17:44 UTC
We need a server for a backend component as well as a database

Minimum DB requirements: 
https://docs.couchbase.com/server/current/install/pre-install.html

The DB will end up being replaced with a service so having them on the same VM saves us future work

**Comment by kj4ezj** [comment] 2022-10-27 20:55
Closing as a duplicate of [issue 80](https://github.com/eosnetworkfoundation/devrel/issues/80).

**Closed by kj4ezj** 2022-10-27 20:55 UTC
