### ISSUE TITLE
Fix double slash in URLs

### ISSUE THREAD

**Issue by nsjames** [eosnetworkfoundation/devrel#194] opened 2023-02-24 10:07 UTC
Please see these 2 Ahrefs reports for

[URLs with double slash](https://docs.google.com/spreadsheets/d/1aYXFgIkCRG5XGWryIEs44JwL_irXVohvKEU5WTFRoV4/edit?usp=share_link)

and

[Links with double slash in URL](https://docs.google.com/spreadsheets/d/1COUAxK36UpYz7qi8iHvCn1PJjYagddrCrXhaEHnFv5g/edit?usp=share_link)

These are also related to the 4XX and 404 pages, that if you fix potentially would complete these fixes as well.

You should have 'Edit' access to the Google docs, please feel free to add your notes there and/or make adjustments. Once done I need to know when the whole is completed. If there are any questions specific to the eosnetwork.com website/domain name please also let me know.

==

**Why and how to fix**

**Issue details**
URLs that contain a double slash (after the domain part).

Most servers are set up to ignore a double slash in the URL path. However, such URLs may be confusing for search engines as they will be interpreted as stand-alone URLs, which can result in duplicate content issues.

**How to fix**
Review the URLs in this report and remove the unnecessary double slashes from their permalinks.

After that, you can check the internal backlinks to the URLs with a double slash and point them to the corrected URL. This will prevent some unnecessary redirects on your website.

==

If you would like to learn more about what triggers these issues, [please visit this article](https://help.ahrefs.com/en/articles/2596665-double-slash-in-url-error-in-site-audit).

**Comment by lparisc** [comment] 2023-04-25 00:15
To reproduce the double slashes in the URLs I went to the production site and searched recursively for the string ".com//". This would catch instances like:

https://docs.eosnetwork.com//welcome/latest/overview/

However, no such instances were found in any of the static html pages. It is possible the double slashes were removed after some internal dependency of the build tool was updated. On either case, the double slashes are not an issue any more, if they ever were.

In relative href's these double slashed URLs won't occur since the browser filters the double slashed automatically, if any, when reconstructing the final URL the browser must navigate to.

Closing as completed.

**Closed by lparisc** 2023-04-25 00:15 UTC
