### ISSUE TITLE
Handle undocumented API changes

### ISSUE THREAD

**Issue by nsjames** [eosnetworkfoundation/devrel#205] opened 2023-03-16 20:28 UTC
https://github.com/AntelopeIO/leap/issues/80

get_transaction_status: https://github.com/AntelopeIO/leap/commit/342edbdf9caf9578360847bbb7817da058b254e3
send_transaction2: https://github.com/AntelopeIO/leap/releases/tag/v3.1.0
compute_transaction: ovi has notes

AC:
- Update [swagger files](https://github.com/AntelopeIO/leap/blob/main/plugins/chain_api_plugin/chain.swagger.yaml) to include
  - get_transaction_status
  - compute_transaction
  - send_transaction2

**Comment by bhazzard** [comment] 2023-04-20 17:39
Closed https://github.com/AntelopeIO/leap/issues/80 as duplicate of this issue.

**Comment by iamveritas** [comment] 2023-04-27 21:18
requires feedback from @ericpassmore because I can't verify it locally, can't generate locally the docs with these changes.

**Comment by ericpassmore** [comment] 2023-04-27 23:06
Updated [docsgen/ehp/how-toupdate-in-place](https://github.com/eosnetworkfoundation/docsgen/tree/ehp/how-to-update-in-place) clean_rebuild.sh to build leap 3.2 and 4.0. 

Currently hardcoded to a personal branch for Leap 4.0 release. Waiting on syntax fix for producer_plugin.swagger.xml before creating PR to merge into staging

**Comment by iamveritas** [comment] 2023-05-04 12:35
PRs that covered this task:
https://github.com/AntelopeIO/leap/pull/1087
https://github.com/AntelopeIO/leap/pull/1110

**Closed by iamveritas** 2023-05-04 12:35 UTC
